/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ChangePasswordViewModel } from '../model/changePasswordViewModel';
import { ErrorViewModel } from '../model/errorViewModel';
import { ForgotPasswordViewModel } from '../model/forgotPasswordViewModel';
import { LoginViewModel } from '../model/loginViewModel';
import { PasswordModel } from '../model/passwordModel';
import { RecoveryCodesViewModel } from '../model/recoveryCodesViewModel';
import { RegisterInvestorViewModel } from '../model/registerInvestorViewModel';
import { RegisterManagerViewModel } from '../model/registerManagerViewModel';
import { ResendConfirmationViewModel } from '../model/resendConfirmationViewModel';
import { ResetPasswordViewModel } from '../model/resetPasswordViewModel';
import { TwoFactorAuthenticator } from '../model/twoFactorAuthenticator';
import { TwoFactorAuthenticatorConfirm } from '../model/twoFactorAuthenticatorConfirm';
import { TwoFactorCodeModel } from '../model/twoFactorCodeModel';
import { TwoFactorStatus } from '../model/twoFactorStatus';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuthService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 2FA confirm
     *
     * @param authorization JWT access token
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10Auth2faConfirmPost(authorization: string, model?: TwoFactorAuthenticatorConfirm, observe?: 'body', reportProgress?: boolean): Observable<RecoveryCodesViewModel>;
    public v10Auth2faConfirmPost(authorization: string, model?: TwoFactorAuthenticatorConfirm, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecoveryCodesViewModel>>;
    public v10Auth2faConfirmPost(authorization: string, model?: TwoFactorAuthenticatorConfirm, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecoveryCodesViewModel>>;
    public v10Auth2faConfirmPost(authorization: string, model?: TwoFactorAuthenticatorConfirm, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10Auth2faConfirmPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<RecoveryCodesViewModel>(`${this.basePath}/v1.0/auth/2fa/confirm`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 2FA create
     *
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10Auth2faCreatePost(authorization: string, observe?: 'body', reportProgress?: boolean): Observable<TwoFactorAuthenticator>;
    public v10Auth2faCreatePost(authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TwoFactorAuthenticator>>;
    public v10Auth2faCreatePost(authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TwoFactorAuthenticator>>;
    public v10Auth2faCreatePost(authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10Auth2faCreatePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<TwoFactorAuthenticator>(`${this.basePath}/v1.0/auth/2fa/create`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 2FA disable
     *
     * @param authorization JWT access token
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10Auth2faDisablePost(authorization: string, model?: TwoFactorCodeModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10Auth2faDisablePost(authorization: string, model?: TwoFactorCodeModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10Auth2faDisablePost(authorization: string, model?: TwoFactorCodeModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10Auth2faDisablePost(authorization: string, model?: TwoFactorCodeModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10Auth2faDisablePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/2fa/disable`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 2FA status
     *
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10Auth2faGet(authorization: string, observe?: 'body', reportProgress?: boolean): Observable<TwoFactorStatus>;
    public v10Auth2faGet(authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TwoFactorStatus>>;
    public v10Auth2faGet(authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TwoFactorStatus>>;
    public v10Auth2faGet(authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10Auth2faGet.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<TwoFactorStatus>(`${this.basePath}/v1.0/auth/2fa`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 2FA generate new recovery codes
     *
     * @param authorization JWT access token
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10Auth2faRecoverycodesNewPost(authorization: string, model?: PasswordModel, observe?: 'body', reportProgress?: boolean): Observable<RecoveryCodesViewModel>;
    public v10Auth2faRecoverycodesNewPost(authorization: string, model?: PasswordModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecoveryCodesViewModel>>;
    public v10Auth2faRecoverycodesNewPost(authorization: string, model?: PasswordModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecoveryCodesViewModel>>;
    public v10Auth2faRecoverycodesNewPost(authorization: string, model?: PasswordModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10Auth2faRecoverycodesNewPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<RecoveryCodesViewModel>(`${this.basePath}/v1.0/auth/2fa/recoverycodes/new`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 2FA recovery codes
     *
     * @param authorization JWT access token
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10Auth2faRecoverycodesPost(authorization: string, model?: PasswordModel, observe?: 'body', reportProgress?: boolean): Observable<RecoveryCodesViewModel>;
    public v10Auth2faRecoverycodesPost(authorization: string, model?: PasswordModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecoveryCodesViewModel>>;
    public v10Auth2faRecoverycodesPost(authorization: string, model?: PasswordModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecoveryCodesViewModel>>;
    public v10Auth2faRecoverycodesPost(authorization: string, model?: PasswordModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10Auth2faRecoverycodesPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<RecoveryCodesViewModel>(`${this.basePath}/v1.0/auth/2fa/recoverycodes`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Change password
     *
     * @param authorization JWT access token
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthPasswordChangePost(authorization: string, model?: ChangePasswordViewModel, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthPasswordChangePost(authorization: string, model?: ChangePasswordViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthPasswordChangePost(authorization: string, model?: ChangePasswordViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthPasswordChangePost(authorization: string, model?: ChangePasswordViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10AuthPasswordChangePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/password/change`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Forgot password for investor
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthPasswordForgotInvestorPost(model?: ForgotPasswordViewModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10AuthPasswordForgotInvestorPost(model?: ForgotPasswordViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10AuthPasswordForgotInvestorPost(model?: ForgotPasswordViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10AuthPasswordForgotInvestorPost(model?: ForgotPasswordViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/password/forgot/investor`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Forgot password for manager
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthPasswordForgotManagerPost(model?: ForgotPasswordViewModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10AuthPasswordForgotManagerPost(model?: ForgotPasswordViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10AuthPasswordForgotManagerPost(model?: ForgotPasswordViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10AuthPasswordForgotManagerPost(model?: ForgotPasswordViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/password/forgot/manager`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reset password
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthPasswordResetPost(model?: ResetPasswordViewModel, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthPasswordResetPost(model?: ResetPasswordViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthPasswordResetPost(model?: ResetPasswordViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthPasswordResetPost(model?: ResetPasswordViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/password/reset`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get phone number verification code
     *
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthPhoneCodePost(authorization: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public v10AuthPhoneCodePost(authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public v10AuthPhoneCodePost(authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public v10AuthPhoneCodePost(authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10AuthPhoneCodePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<number>(`${this.basePath}/v1.0/auth/phone/code`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Verify phone number
     *
     * @param authorization JWT access token
     * @param code
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthPhoneVerifyPost(authorization: string, code?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10AuthPhoneVerifyPost(authorization: string, code?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10AuthPhoneVerifyPost(authorization: string, code?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10AuthPhoneVerifyPost(authorization: string, code?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10AuthPhoneVerifyPost.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (code !== undefined) {
            queryParameters = queryParameters.set('code', <any>code);
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/phone/verify`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Resend Confirmation Link
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthResendconfirmationlinkPost(model?: ResendConfirmationViewModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10AuthResendconfirmationlinkPost(model?: ResendConfirmationViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10AuthResendconfirmationlinkPost(model?: ResendConfirmationViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10AuthResendconfirmationlinkPost(model?: ResendConfirmationViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/resendconfirmationlink`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Authorize
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthSigninInvestorPost(model?: LoginViewModel, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthSigninInvestorPost(model?: LoginViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthSigninInvestorPost(model?: LoginViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthSigninInvestorPost(model?: LoginViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/signin/investor`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Authorize
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthSigninManagerPost(model?: LoginViewModel, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthSigninManagerPost(model?: LoginViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthSigninManagerPost(model?: LoginViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthSigninManagerPost(model?: LoginViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/signin/manager`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Confirm email after registration
     *
     * @param userId
     * @param code
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthSignupConfirmPost(userId?: string, code?: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthSignupConfirmPost(userId?: string, code?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthSignupConfirmPost(userId?: string, code?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthSignupConfirmPost(userId?: string, code?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userId !== undefined) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }
        if (code !== undefined) {
            queryParameters = queryParameters.set('code', <any>code);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/signup/confirm`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * New investor registration
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthSignupInvestorPost(model?: RegisterInvestorViewModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10AuthSignupInvestorPost(model?: RegisterInvestorViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10AuthSignupInvestorPost(model?: RegisterInvestorViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10AuthSignupInvestorPost(model?: RegisterInvestorViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/signup/investor`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * New manager registration
     *
     * @param model
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthSignupManagerPost(model?: RegisterManagerViewModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10AuthSignupManagerPost(model?: RegisterManagerViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10AuthSignupManagerPost(model?: RegisterManagerViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10AuthSignupManagerPost(model?: RegisterManagerViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v1.0/auth/signup/manager`,
            model,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Logout from another devices
     *
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthTokenDevicesLogoutPost(authorization: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthTokenDevicesLogoutPost(authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthTokenDevicesLogoutPost(authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthTokenDevicesLogoutPost(authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10AuthTokenDevicesLogoutPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/token/devices/logout`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update auth token
     *
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10AuthTokenUpdatePost(authorization: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public v10AuthTokenUpdatePost(authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public v10AuthTokenUpdatePost(authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public v10AuthTokenUpdatePost(authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10AuthTokenUpdatePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<string>(`${this.basePath}/v1.0/auth/token/update`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
