/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ErrorViewModel } from '../model/errorViewModel';
import { LevelUpSummary } from '../model/levelUpSummary';
import { ProgramBalanceChart } from '../model/programBalanceChart';
import { ProgramDetailsFull } from '../model/programDetailsFull';
import { ProgramProfitChart } from '../model/programProfitChart';
import { ProgramSets } from '../model/programSets';
import { ProgramsList } from '../model/programsList';
import { TradesViewModel } from '../model/tradesViewModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ProgramsService {

    protected basePath = 'https://black-api.genesis.vision';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Program balance chart
     *
     * @param id
     * @param dateFrom
     * @param dateTo
     * @param maxPointCount
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsByIdChartsBalanceGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe?: 'body', reportProgress?: boolean): Observable<ProgramBalanceChart>;
    public v10ProgramsByIdChartsBalanceGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProgramBalanceChart>>;
    public v10ProgramsByIdChartsBalanceGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProgramBalanceChart>>;
    public v10ProgramsByIdChartsBalanceGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v10ProgramsByIdChartsBalanceGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dateFrom !== undefined) {
            queryParameters = queryParameters.set('DateFrom', <any>dateFrom.toISOString());
        }
        if (dateTo !== undefined) {
            queryParameters = queryParameters.set('DateTo', <any>dateTo.toISOString());
        }
        if (maxPointCount !== undefined) {
            queryParameters = queryParameters.set('MaxPointCount', <any>maxPointCount);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ProgramBalanceChart>(`${this.basePath}/v1.0/programs/${encodeURIComponent(String(id))}/charts/balance`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Program profit chart
     *
     * @param id
     * @param dateFrom
     * @param dateTo
     * @param maxPointCount
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsByIdChartsProfitGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe?: 'body', reportProgress?: boolean): Observable<ProgramProfitChart>;
    public v10ProgramsByIdChartsProfitGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProgramProfitChart>>;
    public v10ProgramsByIdChartsProfitGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProgramProfitChart>>;
    public v10ProgramsByIdChartsProfitGet(id: string, dateFrom?: Date, dateTo?: Date, maxPointCount?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v10ProgramsByIdChartsProfitGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dateFrom !== undefined) {
            queryParameters = queryParameters.set('DateFrom', <any>dateFrom.toISOString());
        }
        if (dateTo !== undefined) {
            queryParameters = queryParameters.set('DateTo', <any>dateTo.toISOString());
        }
        if (maxPointCount !== undefined) {
            queryParameters = queryParameters.set('MaxPointCount', <any>maxPointCount);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ProgramProfitChart>(`${this.basePath}/v1.0/programs/${encodeURIComponent(String(id))}/charts/profit`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add to favorites
     *
     * @param id
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsByIdFavoriteAddPost(id: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10ProgramsByIdFavoriteAddPost(id: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10ProgramsByIdFavoriteAddPost(id: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10ProgramsByIdFavoriteAddPost(id: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v10ProgramsByIdFavoriteAddPost.');
        }
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10ProgramsByIdFavoriteAddPost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/v1.0/programs/${encodeURIComponent(String(id))}/favorite/add`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove from favorites
     *
     * @param id
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsByIdFavoriteRemovePost(id: string, authorization: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v10ProgramsByIdFavoriteRemovePost(id: string, authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v10ProgramsByIdFavoriteRemovePost(id: string, authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v10ProgramsByIdFavoriteRemovePost(id: string, authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v10ProgramsByIdFavoriteRemovePost.');
        }
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10ProgramsByIdFavoriteRemovePost.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/v1.0/programs/${encodeURIComponent(String(id))}/favorite/remove`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Program details
     *
     * @param id
     * @param authorization
     * @param currencySecondary
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsByIdGet(id: string, authorization?: string, currencySecondary?: string, observe?: 'body', reportProgress?: boolean): Observable<ProgramDetailsFull>;
    public v10ProgramsByIdGet(id: string, authorization?: string, currencySecondary?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProgramDetailsFull>>;
    public v10ProgramsByIdGet(id: string, authorization?: string, currencySecondary?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProgramDetailsFull>>;
    public v10ProgramsByIdGet(id: string, authorization?: string, currencySecondary?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v10ProgramsByIdGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (currencySecondary !== undefined) {
            queryParameters = queryParameters.set('currencySecondary', <any>currencySecondary);
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ProgramDetailsFull>(`${this.basePath}/v1.0/programs/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Trade history
     *
     * @param id
     * @param dateFrom
     * @param dateTo
     * @param symbol
     * @param sorting
     * @param skip
     * @param take
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsByIdTradesGet(id: string, dateFrom?: Date, dateTo?: Date, symbol?: string, sorting?: string, skip?: number, take?: number, observe?: 'body', reportProgress?: boolean): Observable<TradesViewModel>;
    public v10ProgramsByIdTradesGet(id: string, dateFrom?: Date, dateTo?: Date, symbol?: string, sorting?: string, skip?: number, take?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TradesViewModel>>;
    public v10ProgramsByIdTradesGet(id: string, dateFrom?: Date, dateTo?: Date, symbol?: string, sorting?: string, skip?: number, take?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TradesViewModel>>;
    public v10ProgramsByIdTradesGet(id: string, dateFrom?: Date, dateTo?: Date, symbol?: string, sorting?: string, skip?: number, take?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v10ProgramsByIdTradesGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dateFrom !== undefined) {
            queryParameters = queryParameters.set('DateFrom', <any>dateFrom.toISOString());
        }
        if (dateTo !== undefined) {
            queryParameters = queryParameters.set('DateTo', <any>dateTo.toISOString());
        }
        if (symbol !== undefined) {
            queryParameters = queryParameters.set('Symbol', <any>symbol);
        }
        if (sorting !== undefined) {
            queryParameters = queryParameters.set('Sorting', <any>sorting);
        }
        if (skip !== undefined) {
            queryParameters = queryParameters.set('Skip', <any>skip);
        }
        if (take !== undefined) {
            queryParameters = queryParameters.set('Take', <any>take);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<TradesViewModel>(`${this.basePath}/v1.0/programs/${encodeURIComponent(String(id))}/trades`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Programs list
     *
     * @param authorization
     * @param levelMin
     * @param levelMax
     * @param profitAvgMin
     * @param profitAvgMax
     * @param sorting
     * @param programCurrency
     * @param currencySecondary
     * @param levelUpFrom
     * @param statisticDateFrom
     * @param statisticDateTo
     * @param chartPointsCount
     * @param mask
     * @param facetId
     * @param isFavorite
     * @param isEnabled
     * @param ids
     * @param managerId
     * @param programManagerId
     * @param skip
     * @param take
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsGet(authorization?: string, levelMin?: number, levelMax?: number, profitAvgMin?: number, profitAvgMax?: number, sorting?: string, programCurrency?: string, currencySecondary?: string, levelUpFrom?: number, statisticDateFrom?: Date, statisticDateTo?: Date, chartPointsCount?: number, mask?: string, facetId?: string, isFavorite?: boolean, isEnabled?: boolean, ids?: Array<string>, managerId?: string, programManagerId?: string, skip?: number, take?: number, observe?: 'body', reportProgress?: boolean): Observable<ProgramsList>;
    public v10ProgramsGet(authorization?: string, levelMin?: number, levelMax?: number, profitAvgMin?: number, profitAvgMax?: number, sorting?: string, programCurrency?: string, currencySecondary?: string, levelUpFrom?: number, statisticDateFrom?: Date, statisticDateTo?: Date, chartPointsCount?: number, mask?: string, facetId?: string, isFavorite?: boolean, isEnabled?: boolean, ids?: Array<string>, managerId?: string, programManagerId?: string, skip?: number, take?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProgramsList>>;
    public v10ProgramsGet(authorization?: string, levelMin?: number, levelMax?: number, profitAvgMin?: number, profitAvgMax?: number, sorting?: string, programCurrency?: string, currencySecondary?: string, levelUpFrom?: number, statisticDateFrom?: Date, statisticDateTo?: Date, chartPointsCount?: number, mask?: string, facetId?: string, isFavorite?: boolean, isEnabled?: boolean, ids?: Array<string>, managerId?: string, programManagerId?: string, skip?: number, take?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProgramsList>>;
    public v10ProgramsGet(authorization?: string, levelMin?: number, levelMax?: number, profitAvgMin?: number, profitAvgMax?: number, sorting?: string, programCurrency?: string, currencySecondary?: string, levelUpFrom?: number, statisticDateFrom?: Date, statisticDateTo?: Date, chartPointsCount?: number, mask?: string, facetId?: string, isFavorite?: boolean, isEnabled?: boolean, ids?: Array<string>, managerId?: string, programManagerId?: string, skip?: number, take?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (levelMin !== undefined) {
            queryParameters = queryParameters.set('LevelMin', <any>levelMin);
        }
        if (levelMax !== undefined) {
            queryParameters = queryParameters.set('LevelMax', <any>levelMax);
        }
        if (profitAvgMin !== undefined) {
            queryParameters = queryParameters.set('ProfitAvgMin', <any>profitAvgMin);
        }
        if (profitAvgMax !== undefined) {
            queryParameters = queryParameters.set('ProfitAvgMax', <any>profitAvgMax);
        }
        if (sorting !== undefined) {
            queryParameters = queryParameters.set('Sorting', <any>sorting);
        }
        if (programCurrency !== undefined) {
            queryParameters = queryParameters.set('ProgramCurrency', <any>programCurrency);
        }
        if (currencySecondary !== undefined) {
            queryParameters = queryParameters.set('CurrencySecondary', <any>currencySecondary);
        }
        if (levelUpFrom !== undefined) {
            queryParameters = queryParameters.set('LevelUpFrom', <any>levelUpFrom);
        }
        if (statisticDateFrom !== undefined) {
            queryParameters = queryParameters.set('StatisticDateFrom', <any>statisticDateFrom.toISOString());
        }
        if (statisticDateTo !== undefined) {
            queryParameters = queryParameters.set('StatisticDateTo', <any>statisticDateTo.toISOString());
        }
        if (chartPointsCount !== undefined) {
            queryParameters = queryParameters.set('ChartPointsCount', <any>chartPointsCount);
        }
        if (mask !== undefined) {
            queryParameters = queryParameters.set('Mask', <any>mask);
        }
        if (facetId !== undefined) {
            queryParameters = queryParameters.set('FacetId', <any>facetId);
        }
        if (isFavorite !== undefined) {
            queryParameters = queryParameters.set('IsFavorite', <any>isFavorite);
        }
        if (isEnabled !== undefined) {
            queryParameters = queryParameters.set('IsEnabled', <any>isEnabled);
        }
        if (ids) {
            ids.forEach((element) => {
                queryParameters = queryParameters.append('Ids', <any>element);
            })
        }
        if (managerId !== undefined) {
            queryParameters = queryParameters.set('ManagerId', <any>managerId);
        }
        if (programManagerId !== undefined) {
            queryParameters = queryParameters.set('ProgramManagerId', <any>programManagerId);
        }
        if (skip !== undefined) {
            queryParameters = queryParameters.set('Skip', <any>skip);
        }
        if (take !== undefined) {
            queryParameters = queryParameters.set('Take', <any>take);
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ProgramsList>(`${this.basePath}/v1.0/programs`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Level up summary
     *
     * @param authorization
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsLevelupSummaryGet(authorization?: string, observe?: 'body', reportProgress?: boolean): Observable<LevelUpSummary>;
    public v10ProgramsLevelupSummaryGet(authorization?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LevelUpSummary>>;
    public v10ProgramsLevelupSummaryGet(authorization?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LevelUpSummary>>;
    public v10ProgramsLevelupSummaryGet(authorization?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<LevelUpSummary>(`${this.basePath}/v1.0/programs/levelup/summary`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Programs sets
     *
     * @param authorization JWT access token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10ProgramsSetsGet(authorization: string, observe?: 'body', reportProgress?: boolean): Observable<ProgramSets>;
    public v10ProgramsSetsGet(authorization: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProgramSets>>;
    public v10ProgramsSetsGet(authorization: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProgramSets>>;
    public v10ProgramsSetsGet(authorization: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling v10ProgramsSetsGet.');
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ProgramSets>(`${this.basePath}/v1.0/programs/sets`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
