/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ErrorViewModel } from '../model/errorViewModel';
import { RatesModel } from '../model/ratesModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RateService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get rate
     *
     * @param exchange
     * @param from
     * @param to
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10RateByExchangeByFromByToGet(exchange: string, from: string, to: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public v10RateByExchangeByFromByToGet(exchange: string, from: string, to: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public v10RateByExchangeByFromByToGet(exchange: string, from: string, to: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public v10RateByExchangeByFromByToGet(exchange: string, from: string, to: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (exchange === null || exchange === undefined) {
            throw new Error('Required parameter exchange was null or undefined when calling v10RateByExchangeByFromByToGet.');
        }
        if (from === null || from === undefined) {
            throw new Error('Required parameter from was null or undefined when calling v10RateByExchangeByFromByToGet.');
        }
        if (to === null || to === undefined) {
            throw new Error('Required parameter to was null or undefined when calling v10RateByExchangeByFromByToGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<number>(`${this.basePath}/v1.0/rate/${encodeURIComponent(String(exchange))}/${encodeURIComponent(String(from))}/${encodeURIComponent(String(to))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get rate
     *
     * @param from
     * @param to
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10RateByFromByToGet(from: string, to: string, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public v10RateByFromByToGet(from: string, to: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public v10RateByFromByToGet(from: string, to: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public v10RateByFromByToGet(from: string, to: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (from === null || from === undefined) {
            throw new Error('Required parameter from was null or undefined when calling v10RateByFromByToGet.');
        }
        if (to === null || to === undefined) {
            throw new Error('Required parameter to was null or undefined when calling v10RateByFromByToGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<number>(`${this.basePath}/v1.0/rate/${encodeURIComponent(String(from))}/${encodeURIComponent(String(to))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get rates
     *
     * @param from
     * @param to
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v10RateGet(from?: Array<string>, to?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<RatesModel>;
    public v10RateGet(from?: Array<string>, to?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatesModel>>;
    public v10RateGet(from?: Array<string>, to?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatesModel>>;
    public v10RateGet(from?: Array<string>, to?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (from) {
            from.forEach((element) => {
                queryParameters = queryParameters.append('from', <any>element);
            })
        }
        if (to) {
            to.forEach((element) => {
                queryParameters = queryParameters.append('to', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<RatesModel>(`${this.basePath}/v1.0/rate`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
