/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AssetsValue {
    type?: AssetsValue.TypeEnum;
    id?: string;
    title?: string;
    avatar?: string;
    color?: string;
    value?: number;
    changePercent?: number;
    changeValue?: number;
}
export namespace AssetsValue {
    export type TypeEnum = 'All' | 'Program' | 'Fund';
    export const TypeEnum = {
        All: 'All' as TypeEnum,
        Program: 'Program' as TypeEnum,
        Fund: 'Fund' as TypeEnum
    }
}
