/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BlockchainInfo {
    hash?: string;
    status?: BlockchainInfo.StatusEnum;
}
export namespace BlockchainInfo {
    export type StatusEnum = 'Undefined' | 'New' | 'Pending' | 'ConfirmedByGate' | 'ConfirmedAndValidated' | 'PendingAddInWallet' | 'Error' | 'Cancelled';
    export const StatusEnum = {
        Undefined: 'Undefined' as StatusEnum,
        New: 'New' as StatusEnum,
        Pending: 'Pending' as StatusEnum,
        ConfirmedByGate: 'ConfirmedByGate' as StatusEnum,
        ConfirmedAndValidated: 'ConfirmedAndValidated' as StatusEnum,
        PendingAddInWallet: 'PendingAddInWallet' as StatusEnum,
        Error: 'Error' as StatusEnum,
        Cancelled: 'Cancelled' as StatusEnum
    }
}
