/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrokerAccountType } from './brokerAccountType';


export interface Broker {
    name?: string;
    description?: string;
    logo?: string;
    terms?: string;
    assets?: string;
    fee?: number;
    leverageMin?: number;
    leverageMax?: number;
    accountTypes?: Array<BrokerAccountType>;
}
