/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BrokerAccountType {
    id?: string;
    name?: string;
    description?: string;
    type?: BrokerAccountType.TypeEnum;
    leverages?: Array<number>;
    currencies?: Array<string>;
}
export namespace BrokerAccountType {
    export type TypeEnum = 'Undefined' | 'MetaTrader4' | 'MetaTrader5' | 'NinjaTrader' | 'cTrader' | 'Rumus' | 'Metastock' | 'IDEX';
    export const TypeEnum = {
        Undefined: 'Undefined' as TypeEnum,
        MetaTrader4: 'MetaTrader4' as TypeEnum,
        MetaTrader5: 'MetaTrader5' as TypeEnum,
        NinjaTrader: 'NinjaTrader' as TypeEnum,
        CTrader: 'cTrader' as TypeEnum,
        Rumus: 'Rumus' as TypeEnum,
        Metastock: 'Metastock' as TypeEnum,
        IDEX: 'IDEX' as TypeEnum
    }
}
