/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardChartValue } from './dashboardChartValue';
import { DashboardPortfolioEvents } from './dashboardPortfolioEvents';
import { ProfileHeaderViewModel } from './profileHeaderViewModel';
import { ProgramRequests } from './programRequests';


export interface DashboardSummary {
    chart?: DashboardChartValue;
    events?: DashboardPortfolioEvents;
    profileHeader?: ProfileHeaderViewModel;
    programsCount?: number;
    fundsCount?: number;
    requests?: ProgramRequests;
}
