/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AmountWithCurrency } from './amountWithCurrency';


export interface FundStatistic {
    balanceGVT?: AmountWithCurrency;
    balanceSecondary?: AmountWithCurrency;
    profitPercent?: number;
    drawdownPercent?: number;
    investorsCount?: number;
    startDate?: Date;
    startBalance?: number;
    investedAmount?: number;
    rebalancingCount?: number;
}
