/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FundAssetPartWithIcon } from './fundAssetPartWithIcon';
import { FundStatistic } from './fundStatistic';
import { PersonalFundDetailsFull } from './personalFundDetailsFull';
import { ProfilePublic } from './profilePublic';


export interface FundDetailsFull {
    entryFee?: number;
    exitFee?: number;
    managementFee?: number;
    currentAssets?: Array<FundAssetPartWithIcon>;
    statistic?: FundStatistic;
    /**
     * Fields for authorized user
     */
    personalFundDetails?: PersonalFundDetailsFull;
    id?: string;
    logo?: string;
    url?: string;
    color?: string;
    description?: string;
    title?: string;
    ipfsHash?: string;
    status?: FundDetailsFull.StatusEnum;
    manager?: ProfilePublic;
}
export namespace FundDetailsFull {
    export type StatusEnum = 'None' | 'Pending' | 'ErrorCreating' | 'Active' | 'Closed' | 'Archived' | 'ClosedDueToInactivity';
    export const StatusEnum = {
        None: 'None' as StatusEnum,
        Pending: 'Pending' as StatusEnum,
        ErrorCreating: 'ErrorCreating' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Closed: 'Closed' as StatusEnum,
        Archived: 'Archived' as StatusEnum,
        ClosedDueToInactivity: 'ClosedDueToInactivity' as StatusEnum
    }
}
