/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChartSimple } from './chartSimple';
import { DashboardProgramDetails } from './dashboardProgramDetails';
import { FundAssetPercent } from './fundAssetPercent';
import { FundDetailsListStatistic } from './fundDetailsListStatistic';
import { PersonalFundDetailsFull } from './personalFundDetailsFull';
import { ProfilePublic } from './profilePublic';


export interface FundDetails {
    totalAssetsCount?: number;
    topFundAssets?: Array<FundAssetPercent>;
    statistic?: FundDetailsListStatistic;
    /**
     * Fields for authorized user
     */
    personalDetails?: PersonalFundDetailsFull;
    id?: string;
    logo?: string;
    url?: string;
    color?: string;
    title?: string;
    description?: string;
    status?: FundDetails.StatusEnum;
    manager?: ProfilePublic;
    chart?: Array<ChartSimple>;
    /**
     * Fields for dashboard
     */
    dashboardAssetsDetails?: DashboardProgramDetails;
}
export namespace FundDetails {
    export type StatusEnum = 'None' | 'Pending' | 'ErrorCreating' | 'Active' | 'Closed' | 'Archived' | 'ClosedDueToInactivity';
    export const StatusEnum = {
        None: 'None' as StatusEnum,
        Pending: 'Pending' as StatusEnum,
        ErrorCreating: 'ErrorCreating' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Closed: 'Closed' as StatusEnum,
        Archived: 'Archived' as StatusEnum,
        ClosedDueToInactivity: 'ClosedDueToInactivity' as StatusEnum
    }
}
