/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ManagerPortfolioEvent {
    assetId?: string;
    date?: Date;
    title?: string;
    value?: number;
    feeValue?: number;
    profitPercent?: number;
    currency?: ManagerPortfolioEvent.CurrencyEnum;
    type?: ManagerPortfolioEvent.TypeEnum;
    programType?: ManagerPortfolioEvent.ProgramTypeEnum;
    logo?: string;
    color?: string;
    description?: string;
    periodNumber?: number;
}
export namespace ManagerPortfolioEvent {
    export type CurrencyEnum = 'Undefined' | 'GVT' | 'ETH' | 'BTC' | 'ADA' | 'USDT' | 'XRP' | 'BCH' | 'LTC' | 'DOGE' | 'BNB' | 'USD' | 'EUR';
    export const CurrencyEnum = {
        Undefined: 'Undefined' as CurrencyEnum,
        GVT: 'GVT' as CurrencyEnum,
        ETH: 'ETH' as CurrencyEnum,
        BTC: 'BTC' as CurrencyEnum,
        ADA: 'ADA' as CurrencyEnum,
        USDT: 'USDT' as CurrencyEnum,
        XRP: 'XRP' as CurrencyEnum,
        BCH: 'BCH' as CurrencyEnum,
        LTC: 'LTC' as CurrencyEnum,
        DOGE: 'DOGE' as CurrencyEnum,
        BNB: 'BNB' as CurrencyEnum,
        USD: 'USD' as CurrencyEnum,
        EUR: 'EUR' as CurrencyEnum
    }
    export type TypeEnum = 'All' | 'AssetStarted' | 'ProgramPeriodStats' | 'ProgramPeriodEnds' | 'InvestorInvest' | 'InvestorWithdraw' | 'ManagerInvest' | 'ManagerWithdraw' | 'AssetFinished' | 'EntranceFee' | 'ExitFee';
    export const TypeEnum = {
        All: 'All' as TypeEnum,
        AssetStarted: 'AssetStarted' as TypeEnum,
        ProgramPeriodStats: 'ProgramPeriodStats' as TypeEnum,
        ProgramPeriodEnds: 'ProgramPeriodEnds' as TypeEnum,
        InvestorInvest: 'InvestorInvest' as TypeEnum,
        InvestorWithdraw: 'InvestorWithdraw' as TypeEnum,
        ManagerInvest: 'ManagerInvest' as TypeEnum,
        ManagerWithdraw: 'ManagerWithdraw' as TypeEnum,
        AssetFinished: 'AssetFinished' as TypeEnum,
        EntranceFee: 'EntranceFee' as TypeEnum,
        ExitFee: 'ExitFee' as TypeEnum
    }
    export type ProgramTypeEnum = 'Program' | 'Fund';
    export const ProgramTypeEnum = {
        Program: 'Program' as ProgramTypeEnum,
        Fund: 'Fund' as ProgramTypeEnum
    }
}
