/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NotificationViewModel {
    id?: string;
    text?: string;
    date?: Date;
    type?: NotificationViewModel.TypeEnum;
    assetId?: string;
    managerId?: string;
    logo?: string;
    url?: string;
    isUnread?: boolean;
    assetType?: NotificationViewModel.AssetTypeEnum;
}
export namespace NotificationViewModel {
    export type TypeEnum = 'PlatformNewsAndUpdates' | 'PlatformEmergency' | 'PlatformOther' | 'ProfileUpdated' | 'ProfilePwdUpdated' | 'ProfileVerification' | 'Profile2FA' | 'ProfileSecurity' | 'ProgramNewsAndUpdates' | 'ProgramEndOfPeriod' | 'ProgramCondition' | 'FundNewsAndUpdates' | 'FundEndOfPeriod' | 'FundRebalancing' | 'ManagerNewProgram';
    export const TypeEnum = {
        PlatformNewsAndUpdates: 'PlatformNewsAndUpdates' as TypeEnum,
        PlatformEmergency: 'PlatformEmergency' as TypeEnum,
        PlatformOther: 'PlatformOther' as TypeEnum,
        ProfileUpdated: 'ProfileUpdated' as TypeEnum,
        ProfilePwdUpdated: 'ProfilePwdUpdated' as TypeEnum,
        ProfileVerification: 'ProfileVerification' as TypeEnum,
        Profile2FA: 'Profile2FA' as TypeEnum,
        ProfileSecurity: 'ProfileSecurity' as TypeEnum,
        ProgramNewsAndUpdates: 'ProgramNewsAndUpdates' as TypeEnum,
        ProgramEndOfPeriod: 'ProgramEndOfPeriod' as TypeEnum,
        ProgramCondition: 'ProgramCondition' as TypeEnum,
        FundNewsAndUpdates: 'FundNewsAndUpdates' as TypeEnum,
        FundEndOfPeriod: 'FundEndOfPeriod' as TypeEnum,
        FundRebalancing: 'FundRebalancing' as TypeEnum,
        ManagerNewProgram: 'ManagerNewProgram' as TypeEnum
    }
    export type AssetTypeEnum = 'Program' | 'Fund';
    export const AssetTypeEnum = {
        Program: 'Program' as AssetTypeEnum,
        Fund: 'Fund' as AssetTypeEnum
    }
}
