/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FundNotificationSettingList } from './fundNotificationSettingList';
import { ManagerNotificationSettingList } from './managerNotificationSettingList';
import { NotificationSettingViewModel } from './notificationSettingViewModel';
import { ProgramNotificationSettingList } from './programNotificationSettingList';


export interface NotificationSettingList {
    settingsGeneral?: Array<NotificationSettingViewModel>;
    settingsProgram?: Array<ProgramNotificationSettingList>;
    settingsFund?: Array<FundNotificationSettingList>;
    settingsManager?: Array<ManagerNotificationSettingList>;
}
