/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrderModel {
    id?: string;
    login?: string;
    ticket?: string;
    symbol?: string;
    volume?: number;
    profit?: number;
    direction?: OrderModel.DirectionEnum;
    date?: Date;
    price?: number;
    entry?: OrderModel.EntryEnum;
}
export namespace OrderModel {
    export type DirectionEnum = 'Buy' | 'Sell' | 'Balance' | 'Credit' | 'Undefined';
    export const DirectionEnum = {
        Buy: 'Buy' as DirectionEnum,
        Sell: 'Sell' as DirectionEnum,
        Balance: 'Balance' as DirectionEnum,
        Credit: 'Credit' as DirectionEnum,
        Undefined: 'Undefined' as DirectionEnum
    }
    export type EntryEnum = 'In' | 'Out' | 'InOut' | 'OutBy';
    export const EntryEnum = {
        In: 'In' as EntryEnum,
        Out: 'Out' as EntryEnum,
        InOut: 'InOut' as EntryEnum,
        OutBy: 'OutBy' as EntryEnum
    }
}
