/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PersonalProgramDetailsFull {
    isReinvest?: boolean;
    gvtValue?: number;
    isFavorite?: boolean;
    isInvested?: boolean;
    isOwnProgram?: boolean;
    canCloseProgram?: boolean;
    isFinishing?: boolean;
    canInvest?: boolean;
    canWithdraw?: boolean;
    canClosePeriod?: boolean;
    hasNotifications?: boolean;
    value?: number;
    profit?: number;
    invested?: number;
    pendingInput?: number;
    pendingOutput?: number;
    status?: PersonalProgramDetailsFull.StatusEnum;
}
export namespace PersonalProgramDetailsFull {
    export type StatusEnum = 'Pending' | 'Active' | 'Investing' | 'Withdrawing' | 'Ended';
    export const StatusEnum = {
        Pending: 'Pending' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Investing: 'Investing' as StatusEnum,
        Withdrawing: 'Withdrawing' as StatusEnum,
        Ended: 'Ended' as StatusEnum
    }
}
