/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProfileHeaderViewModel {
    id?: string;
    name?: string;
    email?: string;
    avatar?: string;
    notificationsCount?: number;
    favoritesCount?: number;
    totalBalanceGvt?: number;
    investedGvt?: number;
    availableGvt?: number;
    kycConfirmed?: boolean;
    isTwoFactorEnabled?: boolean;
    isNewUser?: boolean;
}
