/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProfileFullViewModel {
    id?: string;
    email?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    country?: string;
    city?: string;
    address?: string;
    phone?: string;
    phoneNumberConfirmed?: boolean;
    birthday?: Date;
    gender?: boolean;
    avatar?: string;
    about?: string;
    userName?: string;
    index?: string;
    citizenship?: string;
    refUrl?: string;
    verificationStatus?: ProfileFullViewModel.VerificationStatusEnum;
}
export namespace ProfileFullViewModel {
    export type VerificationStatusEnum = 'NotVerified' | 'Verified' | 'UnderReview' | 'Rejected';
    export const VerificationStatusEnum = {
        NotVerified: 'NotVerified' as VerificationStatusEnum,
        Verified: 'Verified' as VerificationStatusEnum,
        UnderReview: 'UnderReview' as VerificationStatusEnum,
        Rejected: 'Rejected' as VerificationStatusEnum
    }
}
