/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProgramRequest {
    id?: string;
    programId?: string;
    date?: Date;
    value?: number;
    valueGvt?: number;
    feeEntry?: number;
    feeExit?: number;
    currency?: ProgramRequest.CurrencyEnum;
    /**
     * Used only in fund withdraw request
     */
    fundWithdrawPercent?: number;
    type?: ProgramRequest.TypeEnum;
    status?: ProgramRequest.StatusEnum;
    logo?: string;
    title?: string;
    color?: string;
    canCancelRequest?: boolean;
    programType?: ProgramRequest.ProgramTypeEnum;
}
export namespace ProgramRequest {
    export type CurrencyEnum = 'Undefined' | 'GVT' | 'ETH' | 'BTC' | 'ADA' | 'USDT' | 'XRP' | 'BCH' | 'LTC' | 'DOGE' | 'BNB' | 'USD' | 'EUR';
    export const CurrencyEnum = {
        Undefined: 'Undefined' as CurrencyEnum,
        GVT: 'GVT' as CurrencyEnum,
        ETH: 'ETH' as CurrencyEnum,
        BTC: 'BTC' as CurrencyEnum,
        ADA: 'ADA' as CurrencyEnum,
        USDT: 'USDT' as CurrencyEnum,
        XRP: 'XRP' as CurrencyEnum,
        BCH: 'BCH' as CurrencyEnum,
        LTC: 'LTC' as CurrencyEnum,
        DOGE: 'DOGE' as CurrencyEnum,
        BNB: 'BNB' as CurrencyEnum,
        USD: 'USD' as CurrencyEnum,
        EUR: 'EUR' as CurrencyEnum
    }
    export type TypeEnum = 'Invest' | 'Withdrawal';
    export const TypeEnum = {
        Invest: 'Invest' as TypeEnum,
        Withdrawal: 'Withdrawal' as TypeEnum
    }
    export type StatusEnum = 'New' | 'Executed' | 'Cancelled';
    export const StatusEnum = {
        New: 'New' as StatusEnum,
        Executed: 'Executed' as StatusEnum,
        Cancelled: 'Cancelled' as StatusEnum
    }
    export type ProgramTypeEnum = 'Program' | 'Fund';
    export const ProgramTypeEnum = {
        Program: 'Program' as ProgramTypeEnum,
        Fund: 'Fund' as ProgramTypeEnum
    }
}
