/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChartSimple } from './chartSimple';
import { DashboardProgramDetails } from './dashboardProgramDetails';
import { PersonalProgramDetailsFull } from './personalProgramDetailsFull';
import { ProfilePublic } from './profilePublic';
import { ProgramDetailsListStatistic } from './programDetailsListStatistic';
import { ProgramDetailsRating } from './programDetailsRating';


export interface ProgramDetails {
    currency?: ProgramDetails.CurrencyEnum;
    level?: number;
    periodDuration?: number;
    periodStarts?: Date;
    periodEnds?: Date;
    availableInvestment?: number;
    statistic?: ProgramDetailsListStatistic;
    rating?: ProgramDetailsRating;
    /**
     * Fields for authorized user
     */
    personalDetails?: PersonalProgramDetailsFull;
    id?: string;
    logo?: string;
    url?: string;
    color?: string;
    title?: string;
    description?: string;
    status?: ProgramDetails.StatusEnum;
    manager?: ProfilePublic;
    chart?: Array<ChartSimple>;
    /**
     * Fields for dashboard
     */
    dashboardAssetsDetails?: DashboardProgramDetails;
}
export namespace ProgramDetails {
    export type CurrencyEnum = 'Undefined' | 'GVT' | 'ETH' | 'BTC' | 'ADA' | 'USDT' | 'XRP' | 'BCH' | 'LTC' | 'DOGE' | 'BNB' | 'USD' | 'EUR';
    export const CurrencyEnum = {
        Undefined: 'Undefined' as CurrencyEnum,
        GVT: 'GVT' as CurrencyEnum,
        ETH: 'ETH' as CurrencyEnum,
        BTC: 'BTC' as CurrencyEnum,
        ADA: 'ADA' as CurrencyEnum,
        USDT: 'USDT' as CurrencyEnum,
        XRP: 'XRP' as CurrencyEnum,
        BCH: 'BCH' as CurrencyEnum,
        LTC: 'LTC' as CurrencyEnum,
        DOGE: 'DOGE' as CurrencyEnum,
        BNB: 'BNB' as CurrencyEnum,
        USD: 'USD' as CurrencyEnum,
        EUR: 'EUR' as CurrencyEnum
    }
    export type StatusEnum = 'None' | 'Pending' | 'ErrorCreating' | 'Active' | 'Closed' | 'Archived' | 'ClosedDueToInactivity';
    export const StatusEnum = {
        None: 'None' as StatusEnum,
        Pending: 'Pending' as StatusEnum,
        ErrorCreating: 'ErrorCreating' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Closed: 'Closed' as StatusEnum,
        Archived: 'Archived' as StatusEnum,
        ClosedDueToInactivity: 'ClosedDueToInactivity' as StatusEnum
    }
}
