/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AmountWithCurrency } from './amountWithCurrency';


export interface ProgramStatistic {
    balanceBase?: AmountWithCurrency;
    balanceGVT?: AmountWithCurrency;
    balanceSecondary?: AmountWithCurrency;
    currentValue?: number;
    profitPercent?: number;
    profitValue?: number;
    drawdownPercent?: number;
    investorsCount?: number;
    hasNotifications?: boolean;
    startDate?: Date;
    startBalance?: number;
    startCurrency?: ProgramStatistic.StartCurrencyEnum;
    investedAmount?: number;
    investedCurrency?: ProgramStatistic.InvestedCurrencyEnum;
    tradesCount?: number;
    tradesSuccessCount?: number;
    profitFactorPercent?: number;
    sharpeRatioPercent?: number;
}
export namespace ProgramStatistic {
    export type StartCurrencyEnum = 'Undefined' | 'GVT' | 'ETH' | 'BTC' | 'ADA' | 'USDT' | 'XRP' | 'BCH' | 'LTC' | 'DOGE' | 'BNB' | 'USD' | 'EUR';
    export const StartCurrencyEnum = {
        Undefined: 'Undefined' as StartCurrencyEnum,
        GVT: 'GVT' as StartCurrencyEnum,
        ETH: 'ETH' as StartCurrencyEnum,
        BTC: 'BTC' as StartCurrencyEnum,
        ADA: 'ADA' as StartCurrencyEnum,
        USDT: 'USDT' as StartCurrencyEnum,
        XRP: 'XRP' as StartCurrencyEnum,
        BCH: 'BCH' as StartCurrencyEnum,
        LTC: 'LTC' as StartCurrencyEnum,
        DOGE: 'DOGE' as StartCurrencyEnum,
        BNB: 'BNB' as StartCurrencyEnum,
        USD: 'USD' as StartCurrencyEnum,
        EUR: 'EUR' as StartCurrencyEnum
    }
    export type InvestedCurrencyEnum = 'Undefined' | 'GVT' | 'ETH' | 'BTC' | 'ADA' | 'USDT' | 'XRP' | 'BCH' | 'LTC' | 'DOGE' | 'BNB' | 'USD' | 'EUR';
    export const InvestedCurrencyEnum = {
        Undefined: 'Undefined' as InvestedCurrencyEnum,
        GVT: 'GVT' as InvestedCurrencyEnum,
        ETH: 'ETH' as InvestedCurrencyEnum,
        BTC: 'BTC' as InvestedCurrencyEnum,
        ADA: 'ADA' as InvestedCurrencyEnum,
        USDT: 'USDT' as InvestedCurrencyEnum,
        XRP: 'XRP' as InvestedCurrencyEnum,
        BCH: 'BCH' as InvestedCurrencyEnum,
        LTC: 'LTC' as InvestedCurrencyEnum,
        DOGE: 'DOGE' as InvestedCurrencyEnum,
        BNB: 'BNB' as InvestedCurrencyEnum,
        USD: 'USD' as InvestedCurrencyEnum,
        EUR: 'EUR' as InvestedCurrencyEnum
    }
}
