/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RateItem } from './rateItem';


export interface RatesModelRates {
    undefined?: Array<RateItem>;
    GVT?: Array<RateItem>;
    ETH?: Array<RateItem>;
    BTC?: Array<RateItem>;
    ADA?: Array<RateItem>;
    USDT?: Array<RateItem>;
    XRP?: Array<RateItem>;
    BCH?: Array<RateItem>;
    LTC?: Array<RateItem>;
    DOGE?: Array<RateItem>;
    BNB?: Array<RateItem>;
    USD?: Array<RateItem>;
    EUR?: Array<RateItem>;
}
