/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UpdatePersonalDetailViewModel {
    firstName?: string;
    middleName?: string;
    lastName?: string;
    birthday?: Date;
    citizenship?: string;
    gender?: boolean;
    documentId?: string;
    phoneNumber?: string;
    country?: string;
    city?: string;
    address?: string;
    index?: string;
}
