/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetsValue } from './assetsValue';
import { OtherAssetsValue } from './otherAssetsValue';


export interface ValueChartBar {
    value?: number;
    date?: Date;
    topAssets?: Array<AssetsValue>;
    otherAssetsValue?: OtherAssetsValue;
}
