/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface WithdrawalInfo {
    wallet?: string;
    status?: WithdrawalInfo.StatusEnum;
    canResendEmail?: boolean;
    canCancelRequest?: boolean;
}
export namespace WithdrawalInfo {
    export type StatusEnum = 'New' | 'InProcess' | 'Done' | 'Error' | 'Rejected' | 'Cancelled';
    export const StatusEnum = {
        New: 'New' as StatusEnum,
        InProcess: 'InProcess' as StatusEnum,
        Done: 'Done' as StatusEnum,
        Error: 'Error' as StatusEnum,
        Rejected: 'Rejected' as StatusEnum,
        Cancelled: 'Cancelled' as StatusEnum
    }
}
